export const siteConfig = {
  title: 'PT Sakti Pangan Perkasa',
  description: 'PT Sakti Pangan Perkasa adalah perusahaan yang berdedikasi untuk menyediakan produk berkualitas tinggi bagi industri kuliner di Indonesia. Sejak berdiri, kami fokus pada produksi tepung roti atau breadcrumbs yang menjadi bahan baku penting dalam berbagai hidangan.',
  url: 'https://www.saktipangan.co.id',
  ogImage: 'https://www.saktipangan.co.id/favicon.ico',
  author: 'Sakti Food',
  keywords: [
    "pt sakti pangan perkasa",
    "sakti pangan perkasa",
    "saktipangan",
    "saktifood",
    "sakti",
    "laskar",
    "pita",
    "agni",
    "akstar",
    "7daun",
    "fryfest",
    "manufaktur makanan",
    "tepung roti",
    "tepung roti",
    "tepung roti",
    "breadcrumb",
    "breadcrumb",
    "breadcrumb",
    "tepung panir",
    "tepung panir",
    "tepung panir",
    "risol",
    "industri pangan Indonesia",
    "industri tepung roti Indonesia",
    "krispi",
    "kriuk",
    "renyah",
    "karanganyar",
    "jawa tengah"
  ],
  social: {
    instagram: '@sakt1_id',
    tiktok: '@saktitepungroti',
    tokopedia: 'Sakti Pangan Perkasa',
    shopee: 'sakti pangan official',
    linkedin: 'PT Sakti Pangan Perkasa',
  },
  navigation: [
    {
      name: 'Sakti Food - Homepage',
      href: '/',
    },
    {
      name: 'Tentang Kami',
      href: '/about',
    },
    {
      name: 'Sakti Food - product',
      href: '/product',
      children: [
        { name: 'sakti', href: '/product/sakti' },
        { name: 'laskar', href: '/product/laskar' },
        { name: 'agni', href: '/product/agni' },
        { name: 'akstar', href: '/product/akstar' },
        { name: 'pita', href: '/product/pita' },
        { name: '7daun', href: '/product/7daun' },
        { name: 'fryfest', href: '/product/fryfest' },
      ],
    },
    {
      name: 'Blog',
      href: '/blog',
    },
    {
      name: 'Kontak',
      href: '/contact',
    },
    {
      name: 'FAQ',
      href: '/faq',
    },
  ],
};